name: byhub
description: "Byhun - Decentralized Open Source App Store"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  path_provider: ^2.1.1
  http: ^1.1.2
  archive: ^3.4.9
  crypto: ^3.0.3
  file_picker: ^6.1.1
  url_launcher: ^6.2.2
  webview_windows: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
